jobs:
  prepare-android:
    name: Android
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.x
    - continue-on-error: true
      name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build example app
      run: flutter build apk --debug
      working-directory: packages/location/example
    - continue-on-error: true
      name: Run ktlint
      run: ./gradlew :location:ktlintCheck
      working-directory: packages/location/example/android
  prepare-flutter:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: ${{ matrix.flutter-version }}
    - continue-on-error: true
      name: Set up Melos
      run: dart pub global activate melos ^3.0.0
    - continue-on-error: true
      name: melos bootstrap
      run: melos bootstrap
    - continue-on-error: true
      if: success() || failure()
      name: Check code formatting
      run: melos run format --no-select
    - continue-on-error: true
      if: success() || failure()
      name: Run analyzer
      run: melos run analyze --no-select
    - continue-on-error: true
      if: success() || failure()
      name: Run tests
      run: melos run test --no-select
    strategy:
      fail-fast: false
      matrix:
        flutter-version:
        - 3.16.x
        - 3.19.x
  prepare-ios:
    name: iOS
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.16.x
    - continue-on-error: true
      name: Install tools
      run: brew install clang-format
    - continue-on-error: true
      name: clang-format
      run: 'find . -iname ''*.h'' -o -iname ''*.m'' | xargs -I {} clang-format --dry-run
        --Werror {}

        '
      working-directory: packages/location/ios
    - continue-on-error: true
      name: Build example app
      run: flutter build ios --debug --simulator
      working-directory: packages/location/example
name: location prepare
on:
  repository_dispatch:
    types: trigger-ga___location-prepare.yaml
